# Don't print a new line at the start of the prompt
add_newline = true
# Pipes â•°â”€ â•­â”€
# Powerline symbols Â î‚° î‚± î‚² î‚³ î‚´ î‚µ î‚¶ î‚· î‚¸ î‚¹ î‚º î‚» î‚¼ î‚½ î‚¾ î‚¿ îƒ€ îƒ îƒ‚ îƒƒ îƒ„ îƒ… îƒ† îƒ‡ îƒˆ îƒŠ  îƒŒ îƒ îƒ îƒ îƒ îƒ‘ îƒ” îƒ’ 
# Wedges ğŸ­§ğŸ­’ ğŸ­£ğŸ­§ğŸ­“
# Random noise ğŸ¬–ğŸ¬¥ğŸ¬”ğŸ¬—
# Cool stuff ó°œ¥ î©± ï‹ ï€

format = """
$cmd_duration\
$python\
$username$hostname ó°œ¥ $directory $git_branch$git_status\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$docker_context
$character
"""

# format = """
# $cmd_duration ó°œ¥ $directory $git_branch
# $character"""

command_timeout = 5000

# Replace the "â¯" symbol in the prompt with "âœ"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[â•°â”€ â¯â¯ î©± ï‹](bold fg:cyan)"
error_symbol = "[â•°â”€ â¯â¯ ï€ ï‹](bold fg:red)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_branch]
style = "italic cyan"
symbol = "ó°˜¬"
truncation_length = 12
truncation_symbol = ""
format = "ó°œ¥ [î‚¶](bold fg:cyan)[$symbol $branch(:$remote_branch)](fg:black bg:cyan)[î‚´ ](bold fg:cyan)"

[git_commit]
commit_hash_length = 4
tag_symbol = "ï’¶ "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[ğŸ’ PICKING](bold red)"

[git_status]
format     = '[$all_status]($style)'
style      = "cyan"
ahead      = "â‡¡${count} "
diverged   = "â‡•â‡¡${ahead_count}â‡£${behind_count} "
behind     = "â‡£${count} "
conflicted = "î®« "
up_to_date = "ï€Œ "
untracked  = "? "
modified   = "î©± "
stashed    = ""
staged     = ""
renamed    = ""
deleted    = ""

[hostname]
ssh_only = false
format =  "[â€¢$hostname](bg:cyan bold fg:black)[î‚´](bold fg:cyan)"
trim_at = ".companyname.com"
disabled = false

[line_break]
disabled = false

[memory_usage]
disabled = true
threshold = -1
symbol = " "
style = "bold dimmed green"

[time]
disabled = true
format = 'ğŸ•™[\[ $time \]]($style) '
time_format = "%T"

[username]
style_user = "bold bg:cyan fg:black"
style_root = "red bold"
format = "[î‚¶](bold fg:cyan)[$user]($style)"
disabled = false
show_always = true

[directory]
home_symbol = " ï‘­ "
read_only = " ï‘– "
style = "bg:green fg:black"
truncation_length = 6
truncation_symbol = " â€¢â€¢/"
format = '[î‚¶](bold fg:green)[ó°‰‹ $path]($style)[î‚´](bold fg:green)'


[directory.substitutions]
"Desktop" = " ï’© "
"Documents" = " ï’¥ "
"Downloads" = " ï‰ "
"Music" = " ó°ˆ "
"Pictures" = " ï "
"Videos" = " ï”¬ "
"GitHub" = " ó°Š¤ "

[cmd_duration]
min_time = 0
format = '[â•­â”€ î‚¶](bold fg:green)[ó°ª¢ $duration](bold bg:green fg:black)[î‚´](bold fg:green)'

[c]
symbol = "î˜ "
style = "bg:cyan fg:black"
format = 'ó°œ¥ [î‚¶](bold fg:green)[ $symbol ($version) ]($style)[î‚´](bold fg:cyan)'

[docker_context]
symbol = "ïŒˆ "
style = "bg:green fg:black"
format = 'ó°œ¥ [î‚¶](bold fg:green)[ $symbol $context ]($style)$path[î‚´](bold fg:green)'

[elixir]
symbol = "î‰µ "
style = "bg:cyan fg:black"
format = 'ó°œ¥ [î‚¶](bold fg:green)[ $symbol ($version) ]($style)[î‚´](bold fg:cyan)'

[elm]
symbol = "î˜¬ "
style = "bg:cyan fg:black"
format = 'ó°œ¥ [î‚¶](bold fg:green)[ $symbol ($version) ]($style)[î‚´](bold fg:cyan)'

[golang]
symbol = "î˜§ "
style = "bg:cyan fg:black"
format = 'ó°œ¥ [î‚¶](bold fg:green)[ $symbol ($version) ]($style)[î‚´](bold fg:cyan)'

[haskell]
symbol = "î· "
style = "bg:cyan fg:black"
format = 'ó°œ¥ [î‚¶](bold fg:green)[ $symbol ($version) ]($style)[î‚´](bold fg:cyan)'

[java]
symbol = "î‰– "
style = "bg:cyan fg:black"
format = 'ó°œ¥ [î‚¶](bold fg:green)[ $symbol ($version) ]($style)[î‚´](bold fg:cyan)'

[julia]
symbol = "î˜¤ "
style = "bg:cyan fg:black"
format = 'ó°œ¥ [î‚¶](bold fg:green)[ $symbol ($version) ]($style)[î‚´](bold fg:cyan)'

[nodejs]
symbol = "îœ˜"
style = "bg:cyan fg:black"
format = 'ó°œ¥ [î‚¶](bold fg:green)[ $symbol ($version) ]($style)[î‚´](bold fg:cyan)'

[nim]
symbol = "ïš¤ "
style = "bg:cyan fg:black"
format = 'ó°œ¥ [î‚¶](bold fg:green)[ $symbol ($version) ]($style)[î‚´](bold fg:cyan)'

[python]
style = "bg:green fg:black"
format = '[î‚¶](bold fg:green)[(\($virtualenv\))]($style)[î‚´](bold fg:green)'

[rust]
symbol = "î¨"
style = "bg:cyan fg:black"
format = 'ó°œ¥ [î‚¶](bold fg:cyan)[ $symbol ($version) ]($style)[î‚´](bold fg:cyan)'
